### ISSUE TITLE
Unable to use in Angular 7.2.0

### ISSUE THREAD

**Issue by thuannh1027** [crossfilter/crossfilter#147]
I am unable to consume the library in Angular 7.2.0. I install by using `npm i --save dc @types/dc crossfilter2 d3 @types/d3`

Here is my app.component.ts
![crossfilter-error-app component ts](https://user-images.githubusercontent.com/13108786/68569508-cf6c3b80-0490-11ea-97c4-d34c48321a22.PNG)

Here is the error
![crossfilter-error](https://user-images.githubusercontent.com/13108786/68569514-d6934980-0490-11ea-9a2b-b9f21460b343.PNG)

**Comment by gordonwoodhull** [comment]
We just released version 1.5 with ES6 module support, but I don’t know if anyone has tested it with Angular.

Please try changing your dependency to

```json 
  “crossfilter2”: “~1.4”
```
 and see if that works?

**Comment by thuannh1027** [comment]
thank you so much. I will give it a try when I have a chance.

**Comment by gordonwoodhull** [comment]
I don't know that much about Angular or Typescript, but out of curiosity I did some testing.

I took the old test project [ang-dctable](https://github.com/dc-js/ang-dctable) and I upgraded it to Angular 7 and Typescript 3.2. (However, I saw the same errors with Angular 6 and Typescript 2.9.)

It seems that the immediate problem is commit 3a7ed15b112 by @TijmenW. It could be that that using `readonly` in this way is a feature of Typescript > 3.2. Or it could be something else.

Additionally, angular/typescript did not like 

```ts
export = crossfilter
``` 
in `index.d.ts`. 

I got it to build using

```ts
export default crossfilter;
```

Given that Angular Typescript seems to be its own dialect, we probably need a champion for Angular on this project.

**Comment by TijmenW** [comment]
> It seems that the immediate problem is commit 3a7ed15b1127f0be04631b4e8348e36a5a740e4f by @TijmenW. It could be that that using readonly in this way is a feature of Typescript > 3.2. Or it could be something else.

I think that's indeed the case. My apologies, there weren't any Typescript version requirements listed anywhere, and the release was already seven months old.

What would be a possibility is replacing `readonly T[]` by `ReadonlyArray<T>` which is also supported in lower versions and, apparently, in Angular.

**Comment by TijmenW** [comment]
> Additionally, angular/typescript did not like
> 
> ```ts
> export = crossfilter
> ```
> 
> in `index.d.ts`.
> 
> I got it to build using
> 
> ```ts
> export default crossfilter;
> ```

This might be related to the ES6 module rewrite, not sure though.

It might also be a good idea to put in some typescript tests, like [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so this doesn't happen again.

**Comment by gordonwoodhull** [comment]
Yeah, I don’t think anyone tried Angular before, but I’m willing to support it if people want it. Still wish we had a champion for it.

The `export = crossfilter` has been there for two years.

Thanks for the workaround for `readonly`, @TijmenW!

**Comment by TijmenW** [comment]
> The `export = crossfilter` has been there for two years.

Ok, nvm that then.

**Comment by gordonwoodhull** [comment]
I'm going to take careful steps here.

Apparently `export = crossfilter` has different semantics from `export default crossfilter`:

> Unlike default export declarations, which are just shorthand for an export named default, export-equals declarations designate an entity to be exported in place of the actual module.

https://github.com/Microsoft/TypeScript/issues/2242

We are deliberately exporting a function instead of an ordinary module, but I don't know if it makes any difference in `index.d.ts`. I'd like someone to test this before I release it.

I have created a branch `angular-1.4` with @TijmenW's `readonly` fix #148, as well as the export change.

@thuannh1027, or anyone who has an interest in Angular support, please try installing the branch:

```json
    "crossfilter2": "crossfilter/crossfilter#angular-1.4",
```

I'd also appreciate if non-Angular Typescript users could give it a test and report here.

Once I get confirmation that they fix Angular and don't break other uses, I will release 1.4.9 and 1.5.1 with these fixes.

**Comment by thuannh1027** [comment]
Thank you for all your supports. @gordonwoodhull I have tried the new version but it does not work. Here is the error.

![Capture](https://user-images.githubusercontent.com/13108786/68816710-d45c0580-06b1-11ea-98b3-727ff6ed01b3.PNG)

**Comment by gordonwoodhull** [comment]
Thanks @thuannh1027 - which line does this error refer to? 

I am guessing `crossfilter` was not imported as a function. In which case you might be stuck importing crossfilter as JavaScript, since Angular seems to reject export-equals syntax.

**Comment by thuannh1027** [comment]
I try to consume `crossfiler` by `import * as crossfilter from 'crossfilter2'` and after that, I assign my dataset to it. `const testCr = crossfilter(dataset)` - a dataset is an array.

**Comment by gordonwoodhull** [comment]
Yeah the error looks like it is the function call that is failing. I guess you are stuck with unsafe typing, unless someone comes along who knows how to declare a module that is also a function. 😦

**Comment by thuannh1027** [comment]
good news. I think you made it. I try to import by using this `import crossfilter from 'crossfilter2';`. 
it works. 

let me try more and close this ticket if everything's fine.

**Comment by gordonwoodhull** [comment]
Ahhh. This is starting to make sense! Thanks @thuannh1027.

Hopefully someone else can confirm that this branch doesn’t break using typescript without Angular, and we can release this.

**Comment by gordonwoodhull** [comment]
Hi @TijmenW, sorry to lean on you, but I need some feedback here.

1. which syntax do you use to import crossfilter? 
2. does this branch work for you?

I suspect this is a breaking change but it is perhaps more compliant with the ES6 module spec.

**Comment by TijmenW** [comment]
> Hi @TijmenW, sorry to lean on you, but I need some feedback here.
> 
>    1. which syntax do you use to import crossfilter?

Actually, I'm not using Crossfilter currently, but the codebase of the last project we used it in was duct-taped together, so it might not be representative for the usual project. On the frontend we weren't importing crossfilter directly, but instead using UMD globals.  
We weren't using crossfilter on the backend anymore, but when we did it was ```import * as crossfilter from 'crossfilter2';```.
Because of IE, we ran tsc in ES5 mode. 

>    2. does this branch work for you?
> 
> 
> I suspect this is a breaking change but it is perhaps more compliant with the ES6 module spec.

No. While ```import crossfilter from 'crossfilter2';``` compiles fine, it doesn't run.  
TSC compiles 
```ts
import * as crossfilter from 'crossfilter2';
crossfilter()
```
to 
```js
var crossfilter = require("crossfilter2");
crossfilter();
```

But it compiles 
```ts
import crossfilter from 'crossfilter2';
crossfilter();
```
to
```js
var crossfilter2_1 = require("crossfilter2");
crossfilter2_1.default();
```

Since crossfilter has no function named `default`, it crashes when you try to run it. 

`import * as crossfilter from 'crossfilter2';` doesn't work with the new index.d.ts. 

BTW, I'm not sure it's a good idea to require every user to change their import statements. 

I also tried to upgrade crossfilter in our project to 1.5.0 with the new `index.d.ts` added to it, but that didn't work, see the error message from node below, although it's probably caused by the fact that tsc is running in es5 mode.

```
PROJECT\node_modules\crossfilter2\src\index.js:1
import xfilterArray from './array';
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:983:16)
    at Module._compile (internal/modules/cjs/loader.js:1033:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (PROJECT\built\app.js:16:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
```

And again, I'm not sure the project was representative of the usual TypeScript project using crossfilter.

**Comment by gordonwoodhull** [comment]
I agree, we definitely don’t want to change the import syntax. Thanks very much for this analysis!

I guess we’ll have to wait for someone who understands the Angular dialect of Typescript before we release anything for this.

**Comment by rightisleft** [comment]
We're seeing the same thing on our angular 7 builds:

`ERROR in node_modules/crossfilter2/index.d.ts(93,21): error TS1005: ';' expected.
node_modules/crossfilter2/index.d.ts(93,23): error TS1011: An element access expression should take an argument.
node_modules/crossfilter2/index.d.ts(94,18): error TS1005: ';' expected.
node_modules/crossfilter2/index.d.ts(94,22): error TS1011: An element access expression should take an argument.
node_modules/crossfilter2/index.d.ts(95,22): error TS1005: ',' expected.
node_modules/crossfilter2/index.d.ts(95,49): error TS1109: Expression expected.
node_modules/crossfilter2/index.d.ts(95,50): error TS1005: ';' expected.
node_modules/crossfilter2/index.d.ts(95,62): error TS1109: Expression expected.
node_modules/crossfilter2/index.d.ts(96,28): error TS1005: ',' expected.
node_modules/crossfilter2/index.d.ts(96,55): error TS1109: Expression expected.
node_modules/crossfilter2/index.d.ts(96,64): error TS1011: An element access expression should take an argument.
node_modules/crossfilter2/index.d.ts(96,66): error TS1005: ';' expected.
node_modules/crossfilter2/index.d.ts(148,1): error TS1128: Declaration or statement expected.`

Downgrading to 1.4.7 fixed our CI issue for the time being

**Comment by thatcort** [comment]
I've never heard of an Angular "dialect" of Typescript. @gordonwoodhull What are you referring to?

FWIW, my usage of Crossfilter 1.4 in an Angular 7 project look like this:
```
import * as crossfilter from 'crossfilter2/crossfilter';
import {Dimension} from 'crossfilter2';
...
private _crossfilter: crossfilter.Crossfilter<Unit>;
private _allGroup: crossfilter.GroupAll<Unit, number>;
...
this._crossfilter = crossfilter<Unit>();
etc.
```
I think this could probably be improved with a default export to avoid all the `crossfilter.` references.

**Comment by gordonwoodhull** [comment]
@rightisleft, did the special branch help? I am not clear if this helped @thuannh1027 or not.

**Comment by gordonwoodhull** [comment]
@thatcort I’m no Typescript expert, but I am referring to the fact that TS won’t allow you to `export = crossfilter` in order to have a module that is also a function.

I’d love to be proven wrong. If anyone knows what to do here, please jump in!!!

**Comment by thatcort** [comment]
@gordonwoodhull I'm wondering if the crossfilter namespace should be removed. In the Typescript docs there is a section on "Needless Namespacing" that seems applicable: https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html#needless-namespacing

**Comment by gordonwoodhull** [comment]
Thanks @thatcort, that’s interesting but what would we do with the other symbols that currently hang off of `crossfilter`?

https://github.com/crossfilter/crossfilter/wiki/API-Reference#extras

I guess one option is just to drop them, and another option is to make them separate symbols outside of a namespace. Either way `crossfilter` would just be a function.

Neither change is backward compatible. They might affect non-Typescript users as well.

In any case, we need someone to try this stuff out and come up with a proposal, because neither of the active maintainers uses Typescript.

**Comment by thatcort** [comment]
@gordonwoodhull I played around a little bit and here's what I recommend:

Move everything except the "extras" out of the namespace. This will make all the basic Crossfilter types top-level imports. Keeping the extras in the namespace will hang them on the crossfilter function as they are now.

This will mean that existing Typescript users will need to update their import statements, but that's it.

Here's what it looks like when used in an Angular service:

```
import { Injectable } from '@angular/core';
import { Crossfilter, Dimension } from 'crossfilter2';
import * as crossfilter from 'crossfilter2';

interface ITest {
  a: number;
  b: number;
}

@Injectable({
  providedIn: 'root'
})
export class CFServiceService {

  private crossfilter: Crossfilter<ITest>;

  constructor() {
    this.crossfilter = crossfilter<ITest>();
    this.crossfilter.add(this.makeFakeData(5));
    const aDimension: Dimension<ITest, number> = this.crossfilter.dimension<number>((record: ITest) => record.a);

    crossfilter.bisect([1, 2, 3], 2, 0, 2);
  }

  private makeFakeData(count: number): ITest[] {
    return new Array(count).fill(0).map(() => ({a: Math.random(), b: Math.random()}));
  }
}
```

If this seems desirable, I can turn it into a pull-request.

**Comment by gordonwoodhull** [comment]
Thanks @thatcort for experimenting with this.

Are you saying that Angular will allow you to hang other symbols off of a function, just not types?

I was under the impression that there was no way to have a function that is also a module except by using `export = crossfilter`, which Angular does not support.

I'd prefer to find a solution for Angular that does not break the imports of other Typescript users, since everything was working fine for them before. However if we are using a deprecated Typescript feature, then I guess this is inevitable at some point.

**Comment by thatcort** [comment]
I don't think it was ever broken for Angular users, it's just that the imports aren't ergonomic.

See my import example in https://github.com/crossfilter/crossfilter/issues/147#issuecomment-557723760

So this changes the declaration file to allow more ergonomic imports:
`import * as crossfilter from 'crossfilter2/crossfilter';` --> `import * as crossfilter from 'crossfilter2;`

I can understand why this bug was filed. When I was getting started with Crossfilter it was confusing figuring out how to import it correctly.

In general Typescript declarations can model any Javascript construct if you can figure out how to spec it. There is no difference between importing for use in Angular and importing into any other Typescript project.

Btw, I made my modifications based of the master branch. Not sure if that has the ES module work mentioned or changes things in any other way.

**Comment by gordonwoodhull** [comment]
Wait, you’re saying that you are able to use the types from master? That contradicts the original report here. @thuannh1027 reported a syntax error on the `export = crossfilter` line.

Maybe there are different versions of Angular involved here.

**Comment by thatcort** [comment]
Maybe I should test it more thoroughly. I made the changes and `npm link`ed it into a new Angular project, saw all the code completions working and called it good enough to post here. I should try running!

**Comment by thatcort** [comment]
OK, I tried running and got the same error. Apologies. So the original import statements I described above do work. Am I testing on the right branch?

**Comment by gordonwoodhull** [comment]
Thanks for checking, @thatcort.

Yes, the master branch is 1.5 and it has the ES modules stuff. It shouldn't make any difference, since there are no substantive changes to index.d.ts in 1.5 (just a few functions removed). And we kept the API the same.

But I guess you are saying that you were not having problems with 1.4 but with 1.5 you have the same error quoted above. 

I find this hard to explain since index.d.ts has always contained `export = crossfilter` (see dbb50854). The only change is that it was moved to the top level in 0850d95e, which went into 1.4.7... could that be the issue?

**Comment by thatcort** [comment]
I'm saying that I don't have problems with either version, as long as I import correctly as shown in https://github.com/crossfilter/crossfilter/issues/147#issuecomment-557723760

**Comment by gordonwoodhull** [comment]
I’m really confused how importing one way could cause a *syntax error* parsing index.d.ts, but not the other way. That’s not the way I’m used to languages working. I guess I’ll have to dive in and try this stuff myself.

Did you have a working suggestion for how to make this more ergonomic? I suppose we could consider a more streamlined interface in the future. It would require a version bump though.

Thanks for working on this!

**Comment by thatcort** [comment]
The syntax error is due to the declaration file itself, not how it's imported. I honestly find this stuff so confusing sorting out types, namespaces and values, but can try to take another look.

**Comment by Blackbaud-TylerGreen** [comment]
Hey y'all, I'm looking to implement crossfilter with Angular 7. Is there a solution to this? I am running into errors when trying to execute the crossfilter(). Everything compiles, and I am able to go to that function in the source code with my IDE. I get `crossfilter is not a function`. I'm thinking it is related to this?

**Comment by gordonwoodhull** [comment]
This recent thread may help.

It’s too bad that all

**Comment by GChown** [comment]
I've been hitting my head against this for a while using Typescript:
```
import crossfilter from 'crossfilter2';
let x = crossfilter(some_data);
function example(y: crossfilter.Crossfilter<SomeThing>){ ... }
```
With this code, the namespace is recognized but the function isn't.
The code Vivek Raju suggests in the Google Group seems to work:
Change `export = crossfilter` to `export default crossfilter` in line 1 of index.d.ts
Is the solution as simple as that?
Other functions are still accessible: `crossfilter.bisect.by(something)`

**Comment by Blackbaud-TylerGreen** [comment]
The workaround https://github.com/crossfilter/crossfilter/issues/147#issuecomment-617452904 worked for me
`import crossfilter from 'crossfilter2';
import Crossfilter = crossfilter.Crossfilter;
this.crossfilterAttempt = crossfilter(this.dummyDataObjectNames);`

**Comment by Blackbaud-TylerGreen** [comment]
This workaround only works locally however because my builds use a new version of node_modules. I'm not quite sure what needs to be done to solve it, but I think it stems from the namespace and declared function sharing the same name as the export.

**Comment by abhilash-sixthsense** [comment]
@thatcort @Blackbaud-TylerGreen 

The following approach worked for me with Angular 9.

```
import * as crossfilter from 'crossfilter2/crossfilter';
this.crossFilterObj = crossfilter(data);
```

**Comment by vincentpalita** [comment]
@abhilash-sixthsense : are you able to type your crossFilterObj ?
I still have the same error :  This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export. when using Crossfilter interface imported like this : 
import { Crossfilter } from 'crossfilter2'

**Comment by pjpscriv** [comment]
To add a note for Angular 11, I was able to import crossfilter without doing the `index.d.ts` `export = crossfilter` => `export default crossfilter` change, the import just works if I do:

```typescript
import crossfilter from 'crossfilter2';

// ...
crossFilterObj = crossfilter(data)
```

The one extra thing I have to do is add a config value to my `tsconfig.json` to suppress the errors mentioned by @vincentpalita above.
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true
    "..."
  }
  "..."
}

```
