### ISSUE TITLE
Crossfilter 1.4 alpha cannot be used in webpack projects

### ISSUE THREAD

**Issue by hafen** [crossfilter/crossfilter#62]
I was using crossfilter 1.3 with no issues in a webpack project.  When updating to 1.4 alpha (installed from npm), my webpack project gave the following error and wouldn't run:

```
ERROR in ./~/crossfilter2/package.json
Module parse failed: /tmp/myproject/node_modules/crossfilter2/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp.raise (/tmp/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:920:13)
    at Parser.pp.unexpected (/tmp/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:1483:8)
    at Parser.pp.semicolon (/tmp/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:1462:73)
    at Parser.pp.parseExpressionStatement (/tmp/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:1976:8)
    at Parser.pp.parseStatement (/tmp/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:1754:188)
    at Parser.pp.parseBlock (/tmp/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:1991:21)
    at Parser.pp.parseStatement (/tmp/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:1735:19)
    at Parser.pp.parseTopLevel (/tmp/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:1648:21)
    at Parser.parse (/tmp/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:1616:17)
    at Object.parse (/tmp/myproject/node_modules/webpack/node_modules/acorn/dist/acorn.js:882:44)
 @ ./~/crossfilter2/src/crossfilter.js 13:18-46
```

The culprit was the attempt to import package.json to get the version number: https://github.com/crossfilter/crossfilter/blob/master/src/crossfilter.js#L15.  When I omit that line and hard-code the version here https://github.com/crossfilter/crossfilter/blob/master/src/crossfilter.js#L25, it works.  This is of course a temporary fix.

Can we hard-code the version number or find another way to get the version number that is friendly to webpack?

**Comment by esjewett** [comment]
Out of curiosity, is this purely a loader problem? Specifically, could you use [json-loader](https://github.com/webpack/json-loader) and add this to your webpack.config.js?

```
...
module: {
    loaders: [
      {
        // make all files ending in .json use the `json-loader`
        test: /\.json$/,
        loader: 'json-loader'
      }
    ]
  }
...
```

**Comment by esjewett** [comment]
I ask if this works for you, but if it does, we should figure out how to incorporate this into Crossfilter 1.4 itself. I guess we could have our own webpack.config.js? I don't really know how webpack works :-/ Have been meaning to learn though, so maybe this is my big chance :-)

**Comment by hafen** [comment]
That worked!  Thanks!  I don't know enough about webpack (as evidenced by my not realizing this was simply a webpack issue) - I just use it because the project I'm working on is built on it.

**Comment by esjewett** [comment]
Cool - let's actually leave this open. We can probably declare our own dependencies and webpack config so that this issue is solved automatically for others. I'll look into it eventually, or if you or someone else has the time and inclination, feel free to discuss here and open a pull request.

**Comment by betalb** [comment]
Webpack 2 includes json-loader includes json loader by default, so this issue seems to be outdated

**Comment by esjewett** [comment]
@betalb Thanks for the heads-up. Will close in that case.
